version: '3'
services:
  selenoid:
    image: "aerokube/selenoid:latest"
    command: -listen :4444 -conf /etc/selenoid/browsers.json -video-output-dir /opt/selenoid/video/ -log-output-dir /opt/selenoid/logs -timeout 1m -session-attempt-timeout 2m -limit '3' -retry-count '3'
    network_mode: bridge
    ports:
      - "4444:4444"
    volumes:
      - "/c/Users/U6035835/.aerokube/selenoid:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/c/Users/U6035835/.aerokube/selenoid/video/:/opt/selenoid/video" 
      - "/c/Users/U6035835/.aerokube/selenoid/logs/:/opt/selenoid/logs/"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/c/Users/U6035835/.aerokube/selenoid
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    links:
      - selenoid
    ports:
      - "8080:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
